
name: Build and Test with Java 17

on:
  push:
    branches:
      - main
      - beta
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build Pipeline
      run: gradle --build-cache pipeline:build
    - name: Build with Core
      run: gradle --build-cache core:build
    - name: Build with Desktop
      run: gradle --build-cache desktop:build

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Test Pipeline
      run: gradle pipeline:check
    - name: Test Core
      run: gradle core:check